
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wndwtjoxdtknptehtfgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZHd0am94ZHRrbnB0ZWh0Zmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzQ1MjIsImV4cCI6MjA2MzcxMDUyMn0.KZQf8oYH7keYGnC_LtWF3nDkj7DGgJ9uC0Y4X2titSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});

// Force type regeneration by touching the client
console.log('Supabase client initialized with database schema');
